# Generated by Django 4.2.23 on 2025-07-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
