# Generated by Django 4.2.23 on 2025-07-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0002_cancion_spotify_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
    ]
