# Generated by Django 4.2.23 on 2025-07-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0003_album_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
