# Generated by Django 4.2.23 on 2025-07-24 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musica', '0004_alter_album_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseñaartista',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='reseñacancion',
            name='likes',
        ),
        migrations.AddField(
            model_name='comentarioalbum',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='musica.album'),
        ),
        migrations.AddField(
            model_name='comentarioalbum',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentarioalbum',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comentarioalbum',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='musica.comentarioalbum'),
        ),
        migrations.AddField(
            model_name='comentarioalbum',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comentarioartista',
            name='artista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='musica.artista'),
        ),
        migrations.AddField(
            model_name='comentarioartista',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentarioartista',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comentarioartista',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='musica.comentarioartista'),
        ),
        migrations.AddField(
            model_name='comentarioartista',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comentariocancion',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentariocancion',
            name='cancion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='musica.cancion'),
        ),
        migrations.AddField(
            model_name='comentariocancion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comentariocancion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='musica.comentariocancion'),
        ),
        migrations.AddField(
            model_name='comentariocancion',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comentarioalbum',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_comentario_album', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comentarioartista',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_comentario_artista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comentariocancion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_comentario_cancion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='valoracionalbum',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valoracion_set', to='musica.album'),
        ),
        migrations.AlterField(
            model_name='valoracionalbum',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='valoracionalbum',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='valoracionartista',
            name='artista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valoracion_set', to='musica.artista'),
        ),
        migrations.AlterField(
            model_name='valoracionartista',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='valoracionartista',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='valoracioncancion',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='valoracioncancion',
            name='cancion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valoracion_set', to='musica.cancion'),
        ),
        migrations.AlterField(
            model_name='valoracioncancion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='ReseñaAlbum',
        ),
        migrations.DeleteModel(
            name='ReseñaArtista',
        ),
        migrations.DeleteModel(
            name='ReseñaCancion',
        ),
    ]
