# Generated by Django 4.2.23 on 2025-08-07 20:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musica', '0005_remove_reseñaartista_likes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='valoracionalbum',
            unique_together={('autor', 'album')},
        ),
        migrations.AlterUniqueTogether(
            name='valoracionartista',
            unique_together={('autor', 'artista')},
        ),
        migrations.AlterUniqueTogether(
            name='valoracioncancion',
            unique_together={('autor', 'cancion')},
        ),
    ]
