# Generated by Django 4.2.23 on 2025-08-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0006_alter_valoracionalbum_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='letra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
