# Generated by Django 4.2.23 on 2025-08-12 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0007_cancion_letra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracionalbum',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='musica.album'),
        ),
        migrations.AlterField(
            model_name='valoracionartista',
            name='artista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='musica.artista'),
        ),
        migrations.AlterField(
            model_name='valoracioncancion',
            name='cancion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='musica.cancion'),
        ),
    ]
