# Generated by Django 5.2.6 on 2025-09-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0008_alter_valoracionalbum_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
