# Generated by Django 5.2.6 on 2025-10-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0010_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
