# Generated by Django 5.2.6 on 2025-10-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0012_seguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fotoPerfil',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
