# Generated by Django 4.2.23 on 2025-11-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0013_alter_perfil_fotoperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
