# Generated by Django 4.2.23 on 2025-11-17 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musica', '0015_seguimientoartista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientoartista',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('follow', 'Follow'), ('comment', 'Comment'), ('reply', 'Reply'), ('artist', 'Artist Activity'), ('system', 'System')], default='system', max_length=30)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('enlace', models.CharField(blank=True, max_length=500, null=True)),
                ('leido', models.BooleanField(db_index=True, default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('origen_artista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_artista', to='musica.artista')),
                ('origen_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['destinatario', 'leido', 'fecha_creacion'], name='musica_noti_destina_32a213_idx')],
            },
        ),
    ]
