# Generated by Django 5.2.6 on 2025-11-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0016_alter_seguimientoartista_id_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='picks',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
