# Generated by Django 4.2.23 on 2025-12-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0019_spotifytrackfetch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('follow', 'Follow'), ('comment', 'Comment'), ('reply', 'Reply'), ('artist', 'Artist Activity'), ('message', 'Message'), ('system', 'System')], default='system', max_length=30),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
